---
title: "Clean and Tidy Data"
author: "Rebecca Cates"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in Data
```{r}
esc_counts <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", method= "libcurl"), stringsAsFactors = FALSE)

head(esc_counts)

goals_counts <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/knb.92014.1", method= "libcurl"), stringsAsFactors = FALSE)

head(goals_counts)

```
# Escapement Data
```{r}

#filter for BB Sockeye
 
#calculate total escapement by year and stock (location)
  
BB_Sockeye <- esc_counts %>% 
  filter(Species == "Sockeye") %>%
  filter(SASAP.Region == "Bristol Bay") %>% 
  separate(sampleDate, into = c("Year", "Month", "Day"), 
  sep = "-", remove=FALSE)

  
head(BB_Sockeye)

esc_year_location <- BB_Sockeye %>% 
  group_by(Year, Location) %>% 
  summarise(total = sum (DailyCount)) %>% 
  arrange(desc(total))

head(esc_year_location)

#stocks with escapement goals
stock_goals <- goals_counts %>% 
  filter(Region == "Bristol Bay") %>% 
  filter(Species == "Sockeye") %>% 
  mutate(Initial.Year = as.numeric (Initial.Year)) %>% 
  mutate(Lower = ifelse(Lower == "eliminated", NA, Lower)) %>% 
  mutate(Lower = as.numeric(Lower))

#rename column in stock_goals from System to Location
stock_goals <- stock_goals %>% 
  rename(Location = System)

#Identify where a goal exists and join
esc_joined <- inner_join(stock_goals, 
              esc_year_location, by=c("Location")) %>%
              filter(Type != "OEG") %>% 
              filter(Initial.Year >= Year)

stocks_with_goals<- unique(esc_joined$Location)

#proportion escapement by year and stock
goals.met<-esc_joined %>% 
  filter(Initial.Year >= Year) %>%  #by year
  filter(Lower < total & Upper > total) #by stock


```

