---
title: "Data Visualization"
author: "Rebecca Cates"
date: "11/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(leaflet)
library(tidyr)
library(scales)
library(DT)
```

# Prepare Data

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        write.csv(esc, "data/escapement.csv", row.names = F)
        return(esc)
    }
)

head(esc)
```

# Total escapement by Species, Region, Year
  * only for Sockeye, Chinook, Coho, Pink, Chum
```{r}

annual_esc<- esc %>% 
  separate(sampleDate, into = c("Year", "Month", "Day"), 
  sep = "-",  remove=FALSE) %>% 
  mutate(Year = as.numeric(Year)) %>% 
  filter(Species %in% c("Sockeye", "Chinook", "Coho", "Chum", "Pink")) %>%
  group_by(Species, SASAP.Region, Year) %>% 
  summarise(total = sum (DailyCount)) %>% 
  arrange(desc(total))
  
head(annual_esc)
  
  
```


# Create static plots

```{r}
#source of all your bar graphing woes over the last month: fill should not go in the aes parantheses, should go one line below in the geom_graphtype area

ggplot(annual_esc, mapping = aes(x = Species, y = total)) + 
  geom_col(fill = "blue")


```

```{r}
ggplot(annual_esc, mapping=aes(x=Species, y=total, fill = SASAP.Region))+
  geom_col()
```

```{r}
#great way to ensure a continuous theme among users and yourself is to save the theme

my_theme <- theme_bw()+
  theme(legend.position = "bottom")

#can create a palette of colors, want to make sure the number of colors you are using matches the number of variables. For instance:

pal<- c("blue", "green", "khaki", "yellow", "red")

#Then you can stick it into the below graph by using the code line "scale_color_manual(values = pal)"

annual_esc %>% 
  filter(SASAP.Region == "Kodiak") %>% 
  ggplot(mapping = aes(x=Year, y= total, color=Species))+
  geom_line()+
  geom_point()+
  scale_y_continuous(labels = comma)+
  ylab("Escapement (num, fish)")+
  ggtitle("Kodiak Salmon Escapement")+
  theme_bw()+
  theme(legend.position = "bottom")

```
```{r, fig.height = 7, fig.width= 6}

  ggplot(annual_esc, mapping = aes(x=Year, y= total, color=Species))+
  geom_line()+
  geom_point()+
  facet_wrap(~SASAP.Region, ncol=2, scales = "free_y")+
  scale_y_continuous(labels = comma)+
  ylab("Escapement (num, fish)")+
  theme_bw()

```


# Create an interactive table

```{r}
#use distinct instead of select to pull out unique combinations of whatever values you give it

locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

locations
```

```{r}
datatable(locations)
#when you knit the document the table text shows up better
```

# Create an interactive 

```{r}
#leaflet uses a default WGS to project a map with your data overlayed on it

leaflet(locations) %>%
  addTiles() %>%
  addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~Location)
  
  
```
```{r}
#This is different because it adds tiles from a web map server, way to add a different set of tiles, satelite grid tiles instead of open street map tiles

leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```

